all:loaderupr bnumupr palupr teamsupr svetofarsupr \
 cutupr beautifulupr balupr ballanceupr sequenceupr \
 oddupr credupr sheepupr partyupr pairsupr NOI-3.2016.E2.5upr\
 sequpr Eratostenupr zad_za_Ganevaupr digits-3upr flowers \
 teacherupr palindromesupr monoeupr ISBNupr figuresupr\
 datesupr nod expflour cards P123456 airport ants game longest \
 row grid sumdig sumdig-baven kuku
loaderupr:loader2022.cpp
	clang++ loader2022.cpp -o loaderupr 
bnumupr:bnum.cpp
	clang++ bnum.cpp -o bnumupr 
palupr:pal2022.cpp
	clang++ pal2022.cpp  -o palupr 
teamsupr:teams2021.cpp
	clang++ teams2021.cpp  -o teamsupr 
svetofarsupr:sfetofars2021.cpp
	clang++ sfetofars2021.cpp  -o svetofarsupr
cutupr:cuts.cpp
	clang++ cuts.cpp  -o cutupr 
beautifulupr:beautiful.cpp
	clang++ beautiful.cpp -o beautifulupr 
balupr:ball.cpp
	clang++ ball.cpp  -o balupr 
ballanceupr:ballance.cpp
	clang++ ballance.cpp  -o ballanceupr 
sequenceupr:sequence.cpp
	clang++ sequence.cpp  -o sequenceupr 
oddupr:odd-baven.cpp
	clang++ odd-baven.cpp  -o oddupr
credupr:cred.cpp
	clang++ cred.cpp  -o credupr
sheepupr:sheep.cpp
	clang++ sheep.cpp  -o sheepupr
partyupr:party.cpp
	clang++ party.cpp  -o partyupr
pairsupr:pairs.cpp
	clang++ pairs.cpp  -o pairsupr
NOI-3.2016.E2.5upr:NOI-3.2016.E2.5r.cpp
	clang++ NOI-3.2016.E2.5r.cpp  -o NOI-3.2016.E2.5upr
sequpr:seq.cpp
	clang++ seq.cpp  -o sequpr
Eratostenupr:Eratosten.cpp
	clang++ Eratosten.cpp  -o Eratostenupr
zad_za_Ganevaupr:Zad_za_Ganeva.cpp
	clang++ Zad_za_Ganeva.cpp  -o zad_za_Ganevaupr
digits-3upr:digits-3.cpp
	clang++ digits-3.cpp  -o digits-3upr
flowersupr:flowers.cpp
	clang++ flowers.cpp  -o flowersupr
teacherupr:teacher.cpp
	clang++ teacher.cpp  -o teacherupr
palindromesupr:palindromes.cpp
	clang++ palindromes.cpp  -o palindromesupr
monoeupr:monoe.cpp
	clang++ monoe.cpp  -o monoeupr
ISBNupr:ISBN.cpp
	clang++ ISBN.cpp  -o ISBNupr
%upr:%.cpp
	clang++ $?  -o $@