all:loaderupr bnumupr palupr teamsupr svetofarsupr cutupr beautifulupr balupr ballanceupr sequenceupr
loaderupr:loader2022.cpp
	clang++ loader2022.cpp -o loaderupr 
bnumupr:bnum.cpp
	clang++ bnum.cpp -o bnumupr 
palupr:pal2022.cpp
	clang++ pal2022.cpp  -o palupr 
teamsupr:teams2021.cpp
	clang++ teams2021.cpp  -o teamsupr 
svetofarsupr:sfetofars2021.cpp
	clang++ sfetofars2021.cpp  -o svetofarsupr
cutupr:cuts.cpp
	clang++ cuts.cpp  -o cutupr 
beautifulupr:beautiful.cpp
	clang++ beautiful.cpp -o beautifulupr 
balupr:ball.cpp
	clang++ ball.cpp  -o balupr 
ballanceupr:ballance.cpp
	clang++ ballance.cpp  -o ballanceupr 

sequenceupr:sequence.cpp
	clang++ sequence.cpp  -o sequenceupr 

